### ISSUE TITLE
Modify Readme.md

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Multi-Programming#2]
Make any change to learn how to contribute and make PR

**Comment by pathakharsh123** [comment]
please  assign me this issue

**Comment by malivinayak** [comment]
> please assign me this issue
Ohk

**Comment by pathakharsh123** [comment]
ERROR: Permission to malivinayak/Multi-Programming.git denied to pathakharsh123.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
It is showing me this error can you help me resolve this

**Comment by malivinayak** [comment]
Can you tell what exactly you are trying to do

First you have to fork the repo make changes then create PR

**Comment by pathakharsh123** [comment]
I first fixed the repo 
then cloned the repo using the SSH key
then I made my changes then  I used the following command 
git add .
git commit  -m
git push 
on git push it is showing the following message

**Comment by malivinayak** [comment]
You are trying to push the changes on original repo instead of forked one

**Comment by malivinayak** [comment]
Try once again my cloning forked repo
```
git clone https://github.com/pathakharsh123/Multi-Programming.git
```
Make respective changes
```
git add .
git commit -m
git push origin main
```

**Comment by pathakharsh123** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/112664461/195894173-5fa88491-ce72-4dd6-97bb-30a6e9ae2670.png)
I wrote the command you said but it is still showing error .

**Comment by malivinayak** [comment]
```
git log --oneline
```

Send SS of this command

**Comment by pathakharsh123** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/112664461/195903143-d951d91e-17dd-4246-ad75-0beebfac2c01.png)

**Comment by pathakharsh123** [comment]
Sir I have successfully updated the README.md file . 
thank you for helping me out.
please merge my pull request.

**Comment by malivinayak** [comment]
I have merged Your PR #9 

Pro Tip - You want to give reference of other PR or issue in same repo then you can use **#** and that PR or issue number. for e.g. in above line I give reference to your PR which is #9

**Comment by malivinayak** [comment]
If you want to contribute more for open source and for hackoberfest then also check out [this repo](https://github.com/malivinayak/Markdown)
Markdown Repo - [Click Here](https://github.com/malivinayak/Markdown)

In this repo you can add markdown syntax under respective heading

**Comment by pathakharsh123** [comment]
can u tell me will this contribution that I did will be considered as a valuable contribution or not

**Comment by malivinayak** [comment]
This is good first issue contribution
You have successfully updated [How to contribute](https://github.com/malivinayak/Multi-Programming#how-to-contribute) section 
This a valuable contribution as a beginner
